"""Add stars_number column

Revision ID: f1d161c0a969
Revises: dce9f9c4fefb
Create Date: 2024-02-01 19:56:16.211247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d161c0a969'
down_revision = 'dce9f9c4fefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium', schema=None) as batch_op:
        batch_op.drop_column('stars_number')

    # ### end Alembic commands ###
